name: Maria Khalusova
description: Learning, diving into Data Science, ML, Python, and sharing knowledge
url: http://mkhalusova.github.io/
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /blog/:year/:month/:day/:title

