name = "Maria"
license = "MIT"
min_version = "0.53.0"


# If porting an existing theme
[original]
  author = "Alexander Bilz"
  homepage = "https://alexbilz.com"
  repo = "https://github.com/lxndrblz/anatole/"

